<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://order-sg.codashop.com/initPayment.action');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "voucherPricePoint.id=308088&voucherPricePoint.price=450.0&voucherPricePoint.variablePrice=0&email&userVariablePrice=0&user.userId=AMHYM3&user.zoneId&msisdn&voucherTypeName=CALL_OF_DUTY_ACTIVISION&voucherTypeId=183&gvtId=231&shopLang=en_NG&affiliateTrackingId&impactClickId&anonymousId&fullUrl=https%3A%2F%2Fwww.codashop.com%2Fen-ng%2Fcall-of-duty-mobile&userEmailConsent=false&userMobileConsent=false&verifiedMsisdn&promoId&promoCode&clevertapId&promotionReferralCode");

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
$headers[] = 'X-Session-Country2name: NG';
$headers[] = 'Host: order-sg.codashop.com';
$headers[] = 'Origin: https://www.codashop.com';
$headers[] = 'Referer: https://www.codashop.com/';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
print("Username: ".json_decode($result)->confirmationFields->username);
